### ISSUE TITLE
TypeError: _load_sbert_model() received unexpected keyword argument 'token' when initializing INSTRUCTOR model in Colab Notebook

### ISSUE THREAD

**Issue by devin-liu** [xlang-ai/instructor-embedding#125]
<img width="856" alt="image" src="https://github.com/user-attachments/assets/998e375e-3e27-4e30-b41b-c2d8a0b108da">

Running into a TypeError while trying to load the INSTRUCTOR model from the InstructorEmbedding package in a Google Colab notebook. The error message says _load_sbert_model() got an unexpected keyword argument 'token' but I am unaware of how that 'token' argument is getting activated or passed.

**Comment by Adebesin-Aramide** [comment]
Hi, did you figure out the issue?
I'm stuck here as well

**Comment by anhalu** [comment]
I got the same issues, any updated ? I understand that the library only works with SentenceTransformer version 2.2.2 but that version is too old for now. pls update lib version.

**Comment by devin-liu** [comment]
Hey everyone, I managed to get past this step, but I can’t recall the exact way I did it. Here’s the notebook link if someone could run the same commands in the cells I used and report back what was missing in the instructions:

https://colab.research.google.com/gist/devin-liu/be0c89afa78a2750a9fec2ea8e654524/instructor-embedding.ipynb#scrollTo=QFszaK3SsM_F

**Comment by BBC-Esq** [comment]
Please use the "instructor.py" script in my fork of this repository and it should hopefully resolve all issues.  It's compatible with the most recent version of sentence transformers as of the date I'm posting this.  Here's the repo:

https://github.com/BBC-Esq/instructor-embedding

**Comment by iamdebasishdas123** [comment]
!pip install sentence_transformers

from sentence_transformers import SentenceTransformer


model = SentenceTransformer("hkunlp/instructor-large")

It is work without any Error.
